#!/usr/bin/python

import json
import sys

params = sys.argv

package = {
    "name": params[1],
    "version": params[2],
    "description": params[3],
    "author": "lubakka <lboikov2013@gmail.com>",
    "license": "MIT",
    "dependencies": {
        "angular": "latest",
        "angular-animate": "latest",
        "angular-mocks": "latest",
        "angular-local-storage": "latest",
        "angular-resource": "latest",
        "angular-route": "latest",
        "angular-extends": "latest",
        "angular-pagenav": "latest",
        "angular-ckeditor": "latest",
        "bootstrap": "latest",
        "jquery": "latest",
        "noty": "latest",
        "bower": "^1.3.1",
        "http-server": "^0.6.1"
    },
    "scripts": {
        "start": "http-server -a localhost -p 8000 -c-1",
        "update-webdriver": "webdriver-manager update",
    }
}

paths = params[4]
out_file = open( paths, "w")
json.dump(package, out_file, indent=4)
out_file.close()
